spring.application.name=med-delivery

# Render dynamic port use karta hai, isliye port ko variable banayein
server.port=${PORT:8080}

# Database Configurations (Yahan hum variables use karenge jo Render me add karenge)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true