spring.application.name=med-delivery
spring.datasource.url=jdbc:mysql://localhost:3306/med_delivery?useSSL=false&serverTimezone=UTC
spring.datasource.username=local server
spring.datasource.password=bhopal2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port configuration
server.port=8080