spring.application.name=med-delivery

# Railway automatically assigns a port, we read it using ${PORT}
server.port=${PORT:8080}

# Railway MySQL Connection Details using Environment Variables
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true